Add process STAR gene quantification
genialis/resolwe-bio pull request #1247
Opened 2023-02-21 15:39 UTC by OtonicarJan

## Checklist

* [x] Update CHANGELOG.rst for each commit separately:
  * Pay attention to write entries under the "Unreleased" section.
  * Mark all breaking changes as "**BACKWARD INCOMPATIBLE:**" and put them
    before non-breaking changes.
  * If a commit modifies a feature listed under "Unreleased" section,
    it might be sufficient to modify the existing CHANGELOG entry from previous
    commit(s).
* [x] Bump the process version:
  * **MAJOR version (first number)**: Backward incompatible changes (changes
    that break the api/interface). Examples: renaming the input/output, adding
    mandatory input, removing input/output...
  * **MINOR version (middle number)**: add functionality or changes in a
    backwards-compatible manner. Examples: add output field, add non-mandatory
    input parameter, use a different tool that produces same results...
  * **PATCH version (last number)**: changes/bug fixes that do not affect
    the api/interface. Examples: typo fix, change/add warning messages...
* [x] All inputs are used in process.
* [x] All output fields have a value assigned to them.

## Additional guidelines

### Processes ###

* Code that was once accepted should be kept like it is. It should be changed
  only when its functionality has changed. Small parts may be changed
  to fix bugs (by changing code only to make it nicer you might introduce a bug).
* Set the optimal number of cores that the tool can use (check if parallelization
  can be performed).
* Description of the tool should be self explanatory with links to the tool's
  homepage and publication.
* Write explanatory input labels and add short command line parameter names
  in square brackets (for example: Maximum length [``--maxlength``]).
* Where possible provide default values for the process input fields.
  If they are provided, then ``required = False`` is not needed.
* Add descriptive error and warning messages.
* Use ``Cmd()`` for each call in the process (call of a tool, a
  Bash command, a Python script or an R script) and handle return codes.
* Add ``self.progress()`` calls where appropriate.

### Commit and PR messages ###

* Each commit should be minimal (i.e. 1 change) and self-contained (including
  tests).
* Mark incomplete PRs with the [WIP] (Work In Progress) tag.
* Do not paste links to private repositories from the public one.

### Tests ###

* Add meaningful names of test files:
  * Genomes: ``genome_species.fa.gz``
  * Annotations: ``annotation_species.gtf.gz``
  * Adapters: ``adapters-name/type-source``.
* Specific files should be saved in a folder with the name of the tested tool.
  This folder should include separate subfolders for inputs and outputs.
* Keep test files' size small. If there is no other option, add the large
  test file to the ``files/large`` directory so it will be tracked with Git LFS.
* Pay attention to edge cases: what will happen if any data is
  missing, if the length of some list is 0, if a string is given where one
  expects an integer, if a file is empty, ...
* When testing workflows, try to verify workflow success by checking one
  of the last steps. Pick the one that is most likely to fail. Also test
  that all steps have 'OK' status.

2023-02-23 17:24 UTC, romunov requested changes
Overall structure of the process and tests seems fine. There are a few things we should probably address. See inline comments.

2023-02-24 09:28 UTC, OtonicarJan commented on resolwe_bio/processes/expression/star_quantification.py
> +        features = prepare_gene_counts(
`raw_counts` dataframe that is generated with this function is needed for `rnanorm`. I can remove the line `return exp.iloc[4:].index.to_list()` from the function `prepare_gene_counts` and then read the index of `raw_counts` after `rnanorm` to get features?

2023-02-24 09:44 UTC, OtonicarJan commented on resolwe_bio/processes/expression/star_quantification.py
> +            description="If gene counts are not present in the output "
Currently, gene counts are not computed by default in STAR aligner process. They will be computed by default in the RNA-seq, but not all alignments need them (globin, rRNA, Qorts).

2023-02-24 10:38 UTC, romunov commented on resolwe_bio/processes/expression/star_quantification.py
> +        features = prepare_gene_counts(
Forgot about the side effects of the function. Perhaps this should be noted in the comment, something along the lines of

```python
# prepare_gene_counts() has a side effect of creating csv files
# used in rnanorm.
features = prepare_gene_counts(...)
```

2023-02-27 14:23 UTC, jkokosar commented on resolwe_bio/processes/expression/star_quantification.py
> +        normalization_type = StringField(
Let's leave this in.

2023-02-27 14:23 UTC, jkokosar commented on resolwe_bio/processes/expression/star_quantification.py
> +    exp.to_csv(
We do unzip the files before doing the assert in tests, so removing time stamps is not necessary.

2023-02-27 14:23 UTC, jkokosar commented on resolwe_bio/processes/expression/star_quantification.py
> +            "memory": 32768,
Drop the default requirements to 2 cores and 16384 memory. More resources are needed in the case of large Salmon index files (containing a full genome decoy), but not with the smaller index files that are typically used.

2023-02-27 14:23 UTC, jkokosar commented on resolwe_bio/processes/expression/star_quantification.py
> +    """STAR quantification.
I suggest the following description: `Normalize STAR quantification results`. "STAR quantification" wrongly implies that the full quantification by STAR aligner (while aligning) is done here. Modify the class name accordingly.

2023-02-27 19:34 UTC, jkokosar approved these changes

2023-02-28 10:54 UTC, romunov approved these changes

2023-02-28 11:55 UTC, merged